# -*- coding: utf-8 -*-
"""python 11.13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXFRNM37cuM97l-sSQoGalejxCQ_ghi0
"""



import random

# A list of example words, similar to what Wordle might use
word_list = [
    "apple", "baker", "crane", "dream", "eagle",
    "flame", "grape", "house", "igloo", "jolly",
    "knife", "lemon", "mango", "ocean", "peach"
]

# Randomly select a word from the list
chosen_word = random.choice(word_list)

print(f"The generated word is: {chosen_word}")
print(f"The word '{chosen_word}' is invalid in this context.")